# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ASSIGN_STAGE_SHOW_SKELETON_EVENT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&ASSIGN_STAGE_SHOW_SKELETON_EVENT.proto\x12\x08protobuf\"i\n\x11SkeletonDataEvent\x12\x11\n\taccountId\x18\x01 \x01(\x03\x12\x14\n\x0cskeletonData\x18\x02 \x01(\t\x12\x11\n\theartRate\x18\x03 \x01(\x05\x12\x18\n\x10heartRatePercent\x18\x04 \x01(\x05\x42?\n%com.fiture.recording.room.event.protoB\x16SkeletonDataEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ASSIGN_STAGE_SHOW_SKELETON_EVENT_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.fiture.recording.room.event.protoB\026SkeletonDataEventProto'
  _globals['_SKELETONDATAEVENT']._serialized_start=52
  _globals['_SKELETONDATAEVENT']._serialized_end=157
# @@protoc_insertion_point(module_scope)
