# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BOTH_PK_PROGRESS_EVENT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x42OTH_PK_PROGRESS_EVENT.proto\x12\x08protobuf\"?\n\x13\x42othPkProgressEvent\x12(\n\ngroupCount\x18\x01 \x03(\x0b\x32\x14.protobuf.GroupCount\"A\n\nGroupCount\x12\x11\n\tgroupCode\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x11\n\tencourage\x18\x03 \x01(\tBA\n%com.fiture.recording.room.event.protoB\x18\x42othPkProgressEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BOTH_PK_PROGRESS_EVENT_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.fiture.recording.room.event.protoB\030BothPkProgressEventProto'
  _globals['_BOTHPKPROGRESSEVENT']._serialized_start=42
  _globals['_BOTHPKPROGRESSEVENT']._serialized_end=105
  _globals['_GROUPCOUNT']._serialized_start=107
  _globals['_GROUPCOUNT']._serialized_end=172
# @@protoc_insertion_point(module_scope)
