# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BOTH_PK_GROUPING_EVENT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x42OTH_PK_GROUPING_EVENT.proto\x12\x08protobuf\"B\n\x13\x42othPkGroupingEvent\x12+\n\x06groups\x18\x01 \x03(\x0b\x32\x1b.protobuf.PkRoomPlayerGroup\"|\n\x11PkRoomPlayerGroup\x12\x11\n\tgroupCode\x18\x01 \x01(\t\x12\'\n\x07players\x18\x02 \x03(\x0b\x32\x16.protobuf.PkRoomPlayer\x12+\n\x0bshowPlayers\x18\x03 \x03(\x0b\x32\x16.protobuf.PkRoomPlayer\"1\n\x0cPkRoomPlayer\x12\x11\n\taccountId\x18\x01 \x01(\x03\x12\x0e\n\x06\x61vatar\x18\x02 \x01(\tBA\n%com.fiture.recording.room.event.protoB\x18\x42othPkGroupingEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BOTH_PK_GROUPING_EVENT_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.fiture.recording.room.event.protoB\030BothPkGroupingEventProto'
  _globals['_BOTHPKGROUPINGEVENT']._serialized_start=42
  _globals['_BOTHPKGROUPINGEVENT']._serialized_end=108
  _globals['_PKROOMPLAYERGROUP']._serialized_start=110
  _globals['_PKROOMPLAYERGROUP']._serialized_end=234
  _globals['_PKROOMPLAYER']._serialized_start=236
  _globals['_PKROOMPLAYER']._serialized_end=285
# @@protoc_insertion_point(module_scope)
