# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: COACH_GUIDE_DETAIL_EVENT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x43OACH_GUIDE_DETAIL_EVENT.proto\x12\x08protobuf\">\n\x15\x43oachGuideDetailEvent\x12\x0e\n\x06\x64\x65tail\x18\x01 \x01(\t\x12\x15\n\rinteractionId\x18\x02 \x01(\x03\x42\x43\n%com.fiture.recording.room.event.protoB\x1a\x43oachGuideDetailEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'COACH_GUIDE_DETAIL_EVENT_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.fiture.recording.room.event.protoB\032CoachGuideDetailEventProto'
  _globals['_COACHGUIDEDETAILEVENT']._serialized_start=44
  _globals['_COACHGUIDEDETAILEVENT']._serialized_end=106
# @@protoc_insertion_point(module_scope)
