# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: COACH_POST_EMOJI_EVENT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x43OACH_POST_EMOJI_EVENT.proto\x12\x08protobuf\"O\n\x13\x43oachPostEmojiEvent\x12\x12\n\naccountIds\x18\x01 \x03(\x03\x12\x11\n\tguideType\x18\x02 \x01(\t\x12\x11\n\temojiCode\x18\x03 \x01(\tBA\n%com.fiture.recording.room.event.protoB\x18\x43oachPostEmojiEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'COACH_POST_EMOJI_EVENT_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.fiture.recording.room.event.protoB\030CoachPostEmojiEventProto'
  _globals['_COACHPOSTEMOJIEVENT']._serialized_start=42
  _globals['_COACHPOSTEMOJIEVENT']._serialized_end=121
# @@protoc_insertion_point(module_scope)
