# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: COLLECTIVE_CHALLENGE_PROGRESS_EVENT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)COLLECTIVE_CHALLENGE_PROGRESS_EVENT.proto\x12\x08protobuf\"D\n CollectiveChallengeProgressEvent\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x11\n\tencourage\x18\x02 \x01(\tBN\n%com.fiture.recording.room.event.protoB%CollectiveChallengeProgressEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'COLLECTIVE_CHALLENGE_PROGRESS_EVENT_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.fiture.recording.room.event.protoB%CollectiveChallengeProgressEventProto'
  _globals['_COLLECTIVECHALLENGEPROGRESSEVENT']._serialized_start=55
  _globals['_COLLECTIVECHALLENGEPROGRESSEVENT']._serialized_end=123
# @@protoc_insertion_point(module_scope)
