# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: END_ROOM_EVENT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x45ND_ROOM_EVENT.proto\x12\x08protobuf\"T\n\x0c\x45ndRoomEvent\x12\x0e\n\x06roomId\x18\x01 \x01(\x03\x12\x0f\n\x07\x65ndType\x18\x02 \x01(\t\x12\x10\n\x08roomName\x18\x03 \x01(\t\x12\x11\n\tendReason\x18\x04 \x01(\tB:\n%com.fiture.recording.room.event.protoB\x11\x45ndRoomEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'END_ROOM_EVENT_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.fiture.recording.room.event.protoB\021EndRoomEventProto'
  _globals['_ENDROOMEVENT']._serialized_start=34
  _globals['_ENDROOMEVENT']._serialized_end=118
# @@protoc_insertion_point(module_scope)
