# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ENTRY_GROUPING_EVENT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x45NTRY_GROUPING_EVENT.proto\x12\x08protobuf\"D\n\x12\x45ntryGroupingEvent\x12.\n\x06groups\x18\x01 \x03(\x0b\x32\x1e.protobuf.EntryRoomPlayerGroup\"\x8f\x01\n\x14\x45ntryRoomPlayerGroup\x12\x32\n\x07players\x18\x01 \x03(\x0b\x32!.protobuf.EntryGroupingRoomPlayer\x12#\n\x08\x63hannels\x18\x02 \x03(\x0b\x32\x11.protobuf.Channel\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\x10\n\x08sequence\x18\x04 \x01(\x05\"}\n\x17\x45ntryGroupingRoomPlayer\x12\x11\n\taccountId\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x03 \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\x12\x0b\n\x03\x61ge\x18\x05 \x01(\x05\x12\x0e\n\x06gender\x18\x06 \x01(\t\",\n\x07\x43hannel\x12\x13\n\x0btopicSuffix\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\tB@\n%com.fiture.recording.room.event.protoB\x17\x45ntryGroupingEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ENTRY_GROUPING_EVENT_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.fiture.recording.room.event.protoB\027EntryGroupingEventProto'
  _globals['_ENTRYGROUPINGEVENT']._serialized_start=40
  _globals['_ENTRYGROUPINGEVENT']._serialized_end=108
  _globals['_ENTRYROOMPLAYERGROUP']._serialized_start=111
  _globals['_ENTRYROOMPLAYERGROUP']._serialized_end=254
  _globals['_ENTRYGROUPINGROOMPLAYER']._serialized_start=256
  _globals['_ENTRYGROUPINGROOMPLAYER']._serialized_end=381
  _globals['_CHANNEL']._serialized_start=383
  _globals['_CHANNEL']._serialized_end=427
# @@protoc_insertion_point(module_scope)
