# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MC_COACH_REPORT_SKELETON_EVENT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$MC_COACH_REPORT_SKELETON_EVENT.proto\x12\x08protobuf\"F\n\x17HostReportSkeletonEvent\x12\x17\n\x0freportCommandId\x18\x01 \x01(\x03\x12\x12\n\naccountIds\x18\x02 \x03(\x03\x42\x45\n%com.fiture.recording.room.event.protoB\x1cHostReportSkeletonEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MC_COACH_REPORT_SKELETON_EVENT_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.fiture.recording.room.event.protoB\034HostReportSkeletonEventProto'
  _globals['_HOSTREPORTSKELETONEVENT']._serialized_start=50
  _globals['_HOSTREPORTSKELETONEVENT']._serialized_end=120
# @@protoc_insertion_point(module_scope)
