# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PK_SERVER_TRANSFER_PLAYER_DATA_EVENT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*PK_SERVER_TRANSFER_PLAYER_DATA_EVENT.proto\x12\x08protobuf\"\xb9\x01\n\"CollectiveChallengePlayerDataEvent\x12\x0e\n\x06roomId\x18\x01 \x01(\x03\x12\x12\n\nroomItemId\x18\x02 \x01(\x03\x12\x11\n\taccountId\x18\x03 \x01(\x03\x12\r\n\x05score\x18\x04 \x01(\x05\x12\x0c\n\x04unit\x18\x05 \x01(\t\x12\x18\n\x10\x63urrentTimestamp\x18\x06 \x01(\x03\x12\r\n\x05speed\x18\x07 \x01(\x01\x12\x16\n\x0eserverTransfer\x18\x08 \x01(\x08\x42P\n%com.fiture.recording.room.event.protoB\'CollectiveChallengePlayerDataEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PK_SERVER_TRANSFER_PLAYER_DATA_EVENT_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.fiture.recording.room.event.protoB\'CollectiveChallengePlayerDataEventProto'
  _globals['_COLLECTIVECHALLENGEPLAYERDATAEVENT']._serialized_start=57
  _globals['_COLLECTIVECHALLENGEPLAYERDATAEVENT']._serialized_end=242
# @@protoc_insertion_point(module_scope)
