# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PLAYER_ENTRY_EVENT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18PLAYER_ENTRY_EVENT.proto\x12\x08protobuf\"U\n\x10PlayerEnterEvent\x12\x13\n\x0bplayerCount\x18\x01 \x01(\x05\x12,\n\x07players\x18\x02 \x03(\x0b\x32\x1b.protobuf.LatestEnterPlayer\"\xb5\x01\n\x11LatestEnterPlayer\x12\x11\n\taccountId\x18\x01 \x01(\x03\x12\x12\n\nenterOrder\x18\x02 \x01(\x05\x12\x11\n\tavatarUrl\x18\x03 \x01(\t\x12\x10\n\x08userName\x18\x04 \x01(\t\x12\x0e\n\x06gender\x18\x05 \x01(\t\x12\x0b\n\x03\x61ge\x18\x06 \x01(\x05\x12\x10\n\x08location\x18\x07 \x01(\t\x12\r\n\x05roles\x18\x08 \x03(\t\x12\x16\n\x0eroomPlayerType\x18\t \x01(\tB>\n%com.fiture.recording.room.event.protoB\x15PlayerEnterEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PLAYER_ENTRY_EVENT_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.fiture.recording.room.event.protoB\025PlayerEnterEventProto'
  _globals['_PLAYERENTEREVENT']._serialized_start=38
  _globals['_PLAYERENTEREVENT']._serialized_end=123
  _globals['_LATESTENTERPLAYER']._serialized_start=126
  _globals['_LATESTENTERPLAYER']._serialized_end=307
# @@protoc_insertion_point(module_scope)
