# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PLAYER_TRAINING_MOMENT_EVENT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"PLAYER_TRAINING_MOMENT_EVENT.proto\x12\x08protobuf\"\xb3\x04\n\x19PlayerTrainingMomentEvent\x12\x11\n\taccountId\x18\x01 \x01(\x03\x12\x11\n\theartRate\x18\x02 \x01(\x05\x12\x18\n\x10heartRatePercent\x18\x03 \x01(\x05\x12\x10\n\x08\x63\x61lories\x18\x04 \x01(\x03\x12\x15\n\rburningPoints\x18\x05 \x01(\x03\x12\x1a\n\x12skeletonRecognized\x18\x06 \x01(\x08\x12\x15\n\rfakeHeartRate\x18\x07 \x01(\x08\x12\x18\n\x10\x63urrentTimestamp\x18\x08 \x01(\x03\x12:\n\x13movementPerformance\x18\t \x01(\x0b\x32\x1d.protobuf.MovementPerformance\x12\x12\n\nroomItemId\x18\n \x01(\x03\x12\x14\n\x0croomItemType\x18\x0b \x01(\t\x12\x17\n\x0froomItemSubType\x18\x0c \x01(\t\x12\r\n\x05score\x18\r \x01(\x05\x12\x0c\n\x04unit\x18\x0e \x01(\t\x12\x16\n\x0eserverTransfer\x18\x0f \x01(\x08\x12%\n\x06scores\x18\x10 \x03(\x0b\x32\x15.protobuf.PlayerScore\x12$\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x11 \x03(\x0b\x32\x12.protobuf.Feedback\x12*\n\x0bperformance\x18\x12 \x03(\x0b\x32\x15.protobuf.Performance\x12\x18\n\x10trainingRecordId\x18\x13 \x01(\x03\x12\x19\n\x11\x65\x66\x66\x65\x63tiveDuration\x18\x14 \x01(\x03\"H\n\x13MovementPerformance\x12\x12\n\nmovementId\x18\x01 \x01(\x03\x12\x0f\n\x07repeats\x18\x02 \x01(\x03\x12\x0c\n\x04rate\x18\x03 \x01(\x01\"8\n\x0bPlayerScore\x12\r\n\x05score\x18\x01 \x01(\x01\x12\x0c\n\x04unit\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\"6\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07repeats\x18\x02 \x01(\x05\x12\x0c\n\x04type\x18\x03 \x01(\t\".\n\x0bPerformance\x12\x11\n\tresonance\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\tBG\n%com.fiture.recording.room.event.protoB\x1ePlayerTrainingMomentEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PLAYER_TRAINING_MOMENT_EVENT_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.fiture.recording.room.event.protoB\036PlayerTrainingMomentEventProto'
  _globals['_PLAYERTRAININGMOMENTEVENT']._serialized_start=49
  _globals['_PLAYERTRAININGMOMENTEVENT']._serialized_end=612
  _globals['_MOVEMENTPERFORMANCE']._serialized_start=614
  _globals['_MOVEMENTPERFORMANCE']._serialized_end=686
  _globals['_PLAYERSCORE']._serialized_start=688
  _globals['_PLAYERSCORE']._serialized_end=744
  _globals['_FEEDBACK']._serialized_start=746
  _globals['_FEEDBACK']._serialized_end=800
  _globals['_PERFORMANCE']._serialized_start=802
  _globals['_PERFORMANCE']._serialized_end=848
# @@protoc_insertion_point(module_scope)
