# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PLAYER_HIGH_FIVE_EVENT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cPLAYER_HIGH_FIVE_EVENT.proto\x12\x08protobuf\"S\n\x13PlayerHighFiveEvent\x12\x11\n\taccountId\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x18\n\x10\x63urrentTimestamp\x18\x03 \x01(\x03\x42\x41\n%com.fiture.recording.room.event.protoB\x18PlayerHighFiveEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PLAYER_HIGH_FIVE_EVENT_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.fiture.recording.room.event.protoB\030PlayerHighFiveEventProto'
  _globals['_PLAYERHIGHFIVEEVENT']._serialized_start=42
  _globals['_PLAYERHIGHFIVEEVENT']._serialized_end=125
# @@protoc_insertion_point(module_scope)
