# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quick_burning.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13quick_burning.proto\"\xbe\x02\n\x08Protocol\x12\x19\n\x07version\x18\x01 \x01(\x0e\x32\x08.Version\x12\x0e\n\x06srcApp\x18\x02 \x01(\t\x12\x13\n\x06\x64stApp\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05srcId\x18\x04 \x01(\t\x12\x12\n\x05\x64stId\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x0f\n\x07msgCode\x18\x06 \x01(\t\x12\x11\n\x04tags\x18\x07 \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07\x66\x65\x61ture\x18\x08 \x01(\x04H\x03\x88\x01\x01\x12\r\n\x05msgId\x18\t \x01(\t\x12\n\n\x02ts\x18\n \x01(\x03\x12\x10\n\x08priority\x18\x0b \x01(\x05\x12\x13\n\x0b\x63ontentType\x18\x0c \x01(\t\x12\x0f\n\x07payload\x18\r \x01(\x0c\x12\x10\n\x03\x65xt\x18\x0e \x01(\tH\x04\x88\x01\x01\x42\t\n\x07_dstAppB\x08\n\x06_dstIdB\x07\n\x05_tagsB\n\n\x08_featureB\x06\n\x04_ext*\x11\n\x07Version\x12\x06\n\x02V1\x10\x00\x42!\n\x1d\x63om.fiture.digital.mqtt.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quick_burning_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035com.fiture.digital.mqtt.protoP\001'
  _globals['_VERSION']._serialized_start=344
  _globals['_VERSION']._serialized_end=361
  _globals['_PROTOCOL']._serialized_start=24
  _globals['_PROTOCOL']._serialized_end=342
# @@protoc_insertion_point(module_scope)
