# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ROOM_TIMING_LINE_SYNC_EVENT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ROOM_TIMING_LINE_SYNC_EVENT.proto\x12\x08protobuf\"\x8a\x01\n\x17RoomTimingLineSyncEvent\x12\x12\n\nitemOffset\x18\x01 \x01(\x05\x12\x12\n\nroomItemId\x18\x02 \x01(\x03\x12\x11\n\tstartTime\x18\x03 \x01(\x03\x12\x10\n\x08\x64uration\x18\x04 \x01(\x03\x12\x10\n\x08progress\x18\x05 \x01(\x03\x12\x10\n\x08\x63\x61lcTime\x18\x06 \x01(\x03\x42\x45\n%com.fiture.recording.room.event.protoB\x1cRoomTimingLineSyncEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ROOM_TIMING_LINE_SYNC_EVENT_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.fiture.recording.room.event.protoB\034RoomTimingLineSyncEventProto'
  _globals['_ROOMTIMINGLINESYNCEVENT']._serialized_start=48
  _globals['_ROOMTIMINGLINESYNCEVENT']._serialized_end=186
# @@protoc_insertion_point(module_scope)
