# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SEND_ONLINE_PLAYER_EVENT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eSEND_ONLINE_PLAYER_EVENT.proto\x12\x08protobuf\"o\n\x15SendOnlinePlayerEvent\x12\'\n\x07players\x18\x01 \x03(\x0b\x32\x16.protobuf.OnlinePlayer\x12\x13\n\x0bplayerCount\x18\x02 \x01(\x05\x12\x18\n\x10\x63urrentAccountId\x18\x03 \x01(\x03\"C\n\x0cOnlinePlayer\x12\x11\n\taccountId\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x03 \x01(\tBC\n%com.fiture.recording.room.event.protoB\x1aSendOnlinePlayerEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SEND_ONLINE_PLAYER_EVENT_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.fiture.recording.room.event.protoB\032SendOnlinePlayerEventProto'
  _globals['_SENDONLINEPLAYEREVENT']._serialized_start=44
  _globals['_SENDONLINEPLAYEREVENT']._serialized_end=155
  _globals['_ONLINEPLAYER']._serialized_start=157
  _globals['_ONLINEPLAYER']._serialized_end=224
# @@protoc_insertion_point(module_scope)
