# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: START_ROOM_EVENT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16START_ROOM_EVENT.proto\x12\x08protobuf\"i\n\x0eStartRoomEvent\x12\x0e\n\x06roomId\x18\x01 \x01(\x03\x12\x12\n\nroomItemId\x18\x02 \x01(\x03\x12\x1a\n\x12\x63urrentServiceTime\x18\x03 \x01(\x03\x12\x17\n\x0f\x65xpectStartTime\x18\x04 \x01(\x03\x42<\n%com.fiture.recording.room.event.protoB\x13StartRoomEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'START_ROOM_EVENT_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.fiture.recording.room.event.protoB\023StartRoomEventProto'
  _globals['_STARTROOMEVENT']._serialized_start=36
  _globals['_STARTROOMEVENT']._serialized_end=141
# @@protoc_insertion_point(module_scope)
